### ISSUE TITLE
Difficult to add collaborators to a submission

### ISSUE THREAD

**Issue by mattiasstromberg** [NBISweden/fega-sweden-helpdesk-acceptance-testing#19]
**What I tried to do**
I tried to add a collaborator to a submission under the tab 'Submission' by the following actions:

- Writing or copying and pasting the first name of my collaborator in the field 'User'.
- Writing or copying and pasting the first and last name of my collaborator in the field 'User'.
- Copying and pasting the email address of my collaborator.
- Typing the email address of my collaborator.

**What I expected to happen**
I expected that it would be possible to add my collaborator in all four ways.

**What actually happened**
It was only possible to add my collaborator by start typing the email address. Moreover, it was also compulsory to select 'Access Type' in order for the system to find my collaborator. However, 'Access Type' was not indicated as compulsory to specify.

**Steps to reproduce the result**
1. Create a new submission.
2. In the window 'New Submission', check the box 'Add Collaborators'.
3. In the section 'Search Collaborators', select 'User'.
4. In the field 'Search for a User...', search for a collaborator to add by the four action specified above.

**Screenshots**
<img width="937" alt="Add collaborator" src="https://github.com/NBISweden/fega-sweden-helpdesk-acceptance-testing/assets/144035317/deeda926-19c5-4cac-9f84-0d0b72eeb1b2">

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 10

**Comment by mattiasstromberg** [comment]
Confirmed as a bug on 2023-09-27.

**Comment by elisavettorstensson** [comment]
I tried to add a collaborator to the submitter portal today, but it seems the issue hasn't been resolved yet. The only way to add a new collaborator is by manually entering the entire email address. Once that's done, the system recognizes the person and a new window appears with additional information, such as the affiliated university, to identify them. I will write about this issue in the following repository : https://github.com/EGA-archive/FEGA-Portals/issues

**Comment by elisavettorstensson** [comment]
I have reported this issue to the FEGA Portals, and one can find it in the following link: https://github.com/EGA-archive/FEGA-Portals/issues/6. I will close this issue from this repository.
