### ISSUE TITLE
Creating Policy in DAC Portal - error when saving a minimal draft due to empty values in non-mandatory fields

### ISSUE THREAD

**Issue by erikhedman** [NBISweden/fega-sweden-helpdesk-acceptance-testing#24]
**What I tried to do**
I tried to create a minimal draft of a Policy in the DAC Portal. I filled in all mandatory fields and clicked on "CREATE".

**What I expected to happen**
I expected to get some kind of confirmation of the newly created Policy.

**What actually happened**
I was informed "A content or a URL is required", even though these metadata fields are not highlighted as mandatory with a red "wildcard" character. 

**Steps to reproduce the result**
1. Go to the '[DAC Portal](https://dac.ega-archive.org/)' and sign in with your EGA account.
2. Go to 'My Policies' and click on 'Create a Policy' or click directly on 'Create a Policy' from the roll-down menu from the top right corner.
3. Fill in all mandatory fields highlighted with a red "wildcard" character.
4. Click on 'CREATE'

**Screenshots**
![2023-12-04_DAC-Portal_Bug_Creating-new-Policy-error](https://github.com/NBISweden/fega-sweden-helpdesk-acceptance-testing/assets/122466588/e91e1941-cdd7-4589-bbfa-c67f09e93555)

**Desktop (please complete the following information):**
- OS: Windows 10 Education
- Browser: Google Chrome
- Version: 119.0.6045.161

**Additional context**
Incognito mode in Google Chrome was used during the session.

**Comment by jmenglund** [comment]
I checked today and it is now indicated in the GUI that either one of the fields needs to be filled in. I will therefore close this issue.
