### ISSUE TITLE
Unable to see Samples table content inside the Analyses single record entry dialog

### ISSUE THREAD

**Issue by erikhedman** [NBISweden/fega-sweden-helpdesk-acceptance-testing#3]
**Describe the bug**
Inside the single record entry dialog under the Analyses tab, I wanted to display additional columns in the Samples table. The table was populated with more columns but still fit within the same box. With narrower columns, the text was harder to read. No horizontal scrolling appeared. Adding and removing columns made no difference. It was not possible to resize the columns manually. I added more samples to see if this happened vertically as well as horizontally – it did not. More samples caused vertical scrolling to appear.

**To Reproduce**

1. Go to the Submitter Portal and login.
2. Click on the Analyses tab.
3. Click ”ADD ANALYSIS”.
4. Inside the Samples tables, click on the eye symbol and select additional columns to display.

**Expected behavior**
When adding new columns, I expect the table to expand horizontally, so that I can see all the text in each column. Alternatively, I expect that it would be possible to change the width of each column manually.

**Screenshots**
![Skärmavbild 2023-04-24 kl  12 14 50](https://user-images.githubusercontent.com/6959349/233968378-c1d40c7c-2def-46b1-947e-94aad83c28cf.png)

**Desktop (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by rdbjorvang** [comment]
Issue has been fixed.

**Comment by elisavettorstensson** [comment]
As the issue has been fixed according to the recent test, I will close this issue.
